#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define ADC_AVG_TIMES           16U
#define ADC_VREF                3.3f
#define ADC_FULL_SCALE          4095.0f
/*
 * PA4/PA5 按推荐硬件改为 33k / 10k 分压后采样：
 * Vadc = Vnode * 10k / (33k + 10k)
 * 因此软件还原倍率约为 4.3
 */
#define ADC_DIVIDER_RATIO       (10.0f / 43.0f)
#define ADC_INPUT_SCALE         (1.0f / ADC_DIVIDER_RATIO)

#define RELAY_SETTLE_MS         20U
#define ANALOG_SETTLE_MS        8U
#define MEASURE_REPEAT_TIMES    3U
#define MEASURE_SCAN_AVG_TIMES  3U
#define COUNT_SCAN_AVG_TIMES    5U
#define LEARN_SCAN_AVG_TIMES    7U
#define LEARN_SCAN_TRIM_COUNT   1U
#define LEARN_LOW_MIN_SAMPLES   5U
#define LEARN_HIGH_MIN_SAMPLES  3U
#define RESULT_HOLD_MS          1800U
#define DETAILED_RESULT_HOLD_MS 2600U

#define SENSE_RES_LOW_OHM       390.0f
#define SENSE_RES_HIGH_OHM      100.0f
#define SENSE_VALID_MIN_V       0.05f
#define FIXED_DROP_LOW_V        0.04f
#define FIXED_DROP_HIGH_V       0.12f
#define FIXED_DROP_DIR1_LOW_EXTRA_V   0.36f
#define FIXED_DROP_DIR1_HIGH_EXTRA_V  0.36f

#define VF_VALID_MIN            0.10f
#define VF_VALID_MAX            10.50f
#define POLARITY_SCORE_MARGIN   0.02f
#define WEAK_SENSE_MIN_V        0.02f
#define COUNT_MAX_SERIES        10U
#define DIODE_PRESENT_MIN_V     0.08f
#define MODEL_VF_DELTA_MAX      1.20f
#define COUNT_TOL_ONE_TWO       0.10f
#define COUNT_TOL_NORMAL        0.18f
#define COUNT_TOL_HIGH_SERIES   0.24f
#define COUNT_TOL_HIGH_RELAX    0.45f
#define SERIES_FIT_BIAS_V       0.145f
#define SERIES_STEP_MIN_V       0.18f
#define SERIES_FIT_TOL_V        0.20f
#define COUNT_ABC_SCAN_TIMES    5U
#define COUNT_ABC_MARGIN_MIN    0.035f
#define COUNT_ABC_MAX_CANDIDATES 32U
#define COUNT_ABC_MIN_VOTES     2U
#define COUNT_ABC_RELAXED_VOTES 2U
#define COUNT_ABC_ERR_LOW_MAX   0.18f
#define COUNT_ABC_ERR_HIGH_MAX  0.22f
#define COUNT_ABC_ERR_DELTA_MAX 0.35f
#define COUNT_ABC_SCORE_MAX     0.20f

#define FAULT_STEP_EARLY_MS     2U
#define FAULT_STEP_MID_MS       40U
#define FAULT_STEP_LATE_MS      220U
#define FAULT_CAP_MIN_EARLY_V   0.015f
#define FAULT_CAP_DECAY_RATIO   0.55f
#define FAULT_CAP_DROP_MIN_V    0.020f
#define FAULT_CAP_STEADY_DELTA_V    0.015f
#define FAULT_CAP_VDUT_SWING_MIN    0.25f
#define FAULT_OPEN_BOTH_MAX_V       0.08f
#define FAULT_RES_LOW_EXTRA_MIN_V   0.010f
#define FAULT_RES_LOW_EXTRA_MAX_V   0.280f
#define FAULT_RES_HIGH_EXTRA_MIN_V  0.020f
#define FAULT_RES_HIGH_EXTRA_MAX_V  0.500f
#define FAULT_RES_EXTRA_DELTA_MIN_V 0.000f
#define FAULT_RES_EXTRA_DELTA_MAX_V 0.320f
#define FAULT_RES_RESIDUAL_TOL_V    0.080f
#define FAULT_CAP_INVALID_MIN_V     1.00f
#define FAULT_CAP_INVALID_DIFF_MAX  1.20f
#define FAULT_RES_INVALID_MIN_V     0.15f
#define FAULT_RES_INVALID_MAX_V     1.20f
#define FAULT_RES_INVALID_DIFF_MAX  0.80f
#define FAULT_RES_VALID_DIFF_MAX    0.35f

#define RELAY_ACTIVE_LEVEL      GPIO_PIN_SET
#define RELAY_INACTIVE_LEVEL    GPIO_PIN_RESET

#endif
